package game

// EventType represents the category of an event occurring in the game.
// Events are generated by the server to inform the client about gameplay changes.
type EventType uint

const (
	// PlayerAttack is sent after the player performed an attack.
	PlayerAttack EventType = iota

	// HiveAttack is sent after the hive performed an attack.
	HiveAttack

	// GameFinished is sent after the game reached a conclusion.
	GameFinished
)

// Event is a message sent from the server to the client, describing an action
// or state transition in the game. It includes the type of event, a message
// for context, and the current state of the game.
type Event struct {
	Type    EventType // The kind of event that occurred.
	Message string    // A description of what just occurred.
	State   GameState // The current game state after the event.
}
